### ISSUE TITLE
Knative service doesn't appear to update sink address if it changes on GitHubSource

### ISSUE THREAD

**Issue by lbernick** [knative-extensions/eventing-github#346]
**Describe the bug**
I modified the sink of an existing GitHubSource, but it continued to deliver events to the previous sink. I updated the sink from a k8s service named "event-display" to a k8s service named "el-github-listener".

The GitHubSource spec appears correct ([output](https://gist.github.com/lbernick/67dd3e9fb539d61824029f3eb641cd62) of kubectl describe). However, there is a knative service that I'm assuming is responsible for delivering the event payload to my sink (its owner reference is the GitHubSource I created), and its [spec appears wrong](https://gist.github.com/lbernick/26b23163567e5371955f0b3dfb6fdae8). The K_SINK env var is set to "http://event-display.dogfood.svc.cluster.local", i.e. the old address. When I delete this service, a [new one](https://gist.github.com/lbernick/ef132df655ce8741a768cd47c0528a27) is recreated with the correct K_SINK env var (http://el-github-listener.dogfood.svc.cluster.local).

 **Expected behavior**
When I edit the GitHubSource to use a new sink address, it sends events to that sink without having to delete and recreate the GitHubSource.

 **To Reproduce**

Original EventSource config: 
```
apiVersion: sources.knative.dev/v1alpha1
kind: GitHubSource
metadata:
  name: github-push
  namespace: dogfood
spec:
  eventTypes:
    - push
  ownerAndRepository: lbernick/web-app-demo
  accessToken:
    secretKeyRef:
      name: knative-githubsecret
      key: accessToken
  secretToken:
    secretKeyRef:
      name: knative-githubsecret
      key: secretToken
  sink:
    ref:
      url: http://event-display.dogfood.svc.cluster.local
```

I updated the sink to point to http://el-github-listener.dogfood.svc.cluster.local.

 **Knative release version**
 
```
$ kn version
Version:      v1.8.1
Build Date:   2022-10-20 16:09:37
Git Revision: 1db36698
Supported APIs:
* Serving
  - serving.knative.dev/v1 (knative-serving v1.8.0)
* Eventing
  - sources.knative.dev/v1 (knative-eventing v1.8.0)
  - eventing.knative.dev/v1 (knative-eventing v1.8.0)
```
